"""Public protocol model exports."""

from typing import TYPE_CHECKING, Any
from importlib import import_module

if TYPE_CHECKING:
    from .common import (
        AttachmentId,
        ClientId,
        ClientInfo,
        CompatibilityResult,
        ConnectionId,
        CoreInfo,
        ForwardId,
        InteractionId,
        RequestId,
        SessionId,
        SftpServiceId,
        TransferId,
    )
    from .connection_store import (
        AddTagToConnectionsRequest,
        ConnectionMetadataSummary,
        ConnectionPlacementMode,
        ConnectionStoreSnapshot,
        CopyConnectionToGroupRequest,
        MoveConnectionsRequest,
        GroupId,
        GroupSummary,
        PlaceGroupRequest,
        RemoveConnectionFromGroupRequest,
        RenameTagRequest,
        ReorderConnectionRequest,
        SetGroupColorRequest,
    )
    from .connections import (
        AsbruImportMessage,
        AsbruImportMessageCode,
        AsbruImportMode,
        AsbruImportPreview,
        AsbruImportRequest,
        AsbruImportResult,
        AssignConnectionToGroupRequest,
        AuthenticationMethod,
        ConnectionDetails,
        ConnectionEditorCapabilities,
        ConnectionEditorDetails,
        EffectiveConfigComparison,
        UnsavedHostCheckRequest,
        UnsavedHostCheckResult,
        ConnectionHealth,
        ConnectionMutationResult,
        ConnectionSummary,
        ConnectionValidationError,
        ConnectionValidationResult,
        CreateConnectionRequest,
        CreateGroupRequest,
        DeleteConnectionRequest,
        DeleteConnectionResult,
        DeleteConnectionPasswordRequest,
        DeleteGroupRequest,
        DeleteKeyPassphraseRequest,
        DeletePluginSecretRequest,
        EDITABLE_CONFIG_FIELDS,
        ForwardingRule,
        FORBIDDEN_IN_PATCH,
        GetPluginSecretRequest,
        GroupReference,
        LookupKeyPassphraseRequest,
        RenameGroupRequest,
        SaveSshConfigTextRequest,
        SplitConnectionRequest,
        SshConfigText,
        StoreConnectionPasswordRequest,
        SetSessionConnectionPasswordRequest,
        StoreKeyPassphraseRequest,
        StorePluginSecretRequest,
        UNSET,
        UpdateConnectionMetadataRequest,
        UpdateConnectionRequest,
        forwarding_rule_from_dict,
        forwarding_rule_to_dict,
        validate_config_patch,
    )
    from .daemon import (
        DaemonDiagnostics,
        DaemonDisconnectReason,
        DaemonIdleInfo,
        DaemonLifecycleState,
        DaemonLogLevel,
        DaemonResourceCounts,
        DaemonStatus,
        DaemonStopResult,
        RestartDaemonRequest,
        SetDaemonLogLevelRequest,
        OperationMode,
        OperationModeFiles,
        OperationModeResult,
        SetOperationModeRequest,
        StopDaemonRequest,
        default_idle_shutdown_seconds,
        is_valid_lifecycle_transition,
    )
    from .interactions import (
        ChallengePrompt,
        ConfirmationPrompt,
        HostKeyDecision,
        HostKeyPrompt,
        HostKeyStatus,
        InteractionClaim,
        InteractionCancellation,
        InteractionDecisionRequest,
        InteractionKind,
        InteractionPrompt,
        InteractionRejection,
        InteractionRequest,
        InteractionResponse,
        InteractionState,
        InteractionStatus,
        InteractionSummary,
        InteractionTimeout,
        InteractionType,
        PassphrasePrompt,
        PasswordPrompt,
        PresencePrompt,
        RememberPolicy,
        SecretDecision,
        SecretPromptKind,
    )
    from .keys import (
        DeleteKeyRequest,
        DeleteKeyResult,
        GenerateKeyRequest,
        GenerateKeyResult,
        KeyId,
        KeyList,
        KeyStoreScope,
        KeySummary,
        ListKeysRequest,
        PublicKeyResult,
        ReadPublicKeyRequest,
        VerifyKeyPassphraseRequest,
        VerifyKeyPassphraseResult,
    )
    from .identity import (
        AgentKey,
        AgentKeyList,
        AgentKeyMutationRequest,
        AuthorizedKeyEntry,
        AuthorizedKeyLineKind,
        AuthorizedKeyList,
        DeployKeyRequest,
        FetchPublicKeysRequest,
        IdentityProviderDescriptor,
        IdentityProviderRegistry,
        IdentityState,
        ImportedPublicKey,
        ImportedPublicKeyList,
        ListAuthorizedKeysRequest,
        RemoveAuthorizedKeyRequest,
        UpdateIdentityConfigurationRequest,
        UpdateIdentitySelectionRequest,
    )
    from .host_info import (
        CpuInfo,
        CpuTimes,
        CpuUtilization,
        FailedUnit,
        FilesystemUsage,
        HostInfoFailure,
        HostInfoFailureCode,
        HostInfoProbe,
        HostInfoRequest,
        HostInfoSnapshot,
        HostInfoSummary,
        HostKeyFingerprint,
        InterfaceCounters,
        ListeningPort,
        LiveSample,
        LoadAverage,
        LoginSession,
        MemoryInfo,
        NetworkInterface,
        NetworkInterfaceKind,
        NetworkInterfaceState,
        PressureStall,
        ProcessCounts,
        ProcessUsage,
        SocketConnection,
        SocketDirection,
        TemperatureReading,
    )
    from .known_hosts import (
        KnownHostEntryId,
        KnownHostEntrySummary,
        KnownHostsMutationResult,
        KnownHostsSnapshot,
        RemoveKnownHostEntriesRequest,
    )
    from .operations import (
        AttachSftpRequest,
        ClaimForwardRequest,
        CloseForwardRequest,
        CloseSftpRequest,
        FileEntryKind,
        ForwardKind,
        ForwardState,
        ForwardSummary,
        ForwardType,
        IdentityFailure,
        IdentityFailureCode,
        ListDirectoryRequest,
        ListDirectoryResult,
        OpenForwardRequest,
        OpenSftpRequest,
        OperationId,
        OperationKind,
        OperationState,
        OperationSummary,
        PluginArgument,
        PluginOperationRequest,
        PluginOperationResult,
        PortForwardSummary,
        RemoteFileEntry,
        RemoteFileType,
        ScpFailure,
        ScpFailureCode,
        ServiceFailure,
        SftpFailure,
        SftpFailureCode,
        SftpChmodRequest,
        SftpCopyRequest,
        SftpCreateFileRequest,
        SftpCreateFileResult,
        SftpDirectorySizeRequest,
        SftpDirectorySizeResult,
        SftpEntry,
        SftpFileAccess,
        SftpFileTarget,
        SftpFilesystemUsage,
        SftpPathRequest,
        SftpRemoveFailure,
        SftpRemoveResult,
        SftpReadFileRequest,
        SftpReadFileResult,
        SftpRenameRequest,
        SftpReplaceFileRequest,
        SftpReplaceFileResult,
        SftpServiceState,
        SftpServiceSummary,
        SftpSymlinkRequest,
        is_terminal_operation_state,
        is_valid_operation_transition,
    )
    from .broadcast import (
        BroadcastCommandRequest,
        BroadcastCommandSummary,
        BroadcastCommandOutput,
        BroadcastExecutionPolicy,
        BroadcastFailurePolicy,
        HostCommandResult,
        HostCommandState,
    )
    from .pre_command import (
        PreCommandLaunchKind,
        PreCommandMode,
        PreCommandPhase,
        PreCommandReason,
        PreCommandStage,
        PreConnectionCommandNotice,
    )
    from .interactions import ExecutionInteractionMode
    from .sessions import (
        AttachSessionRequest,
        AttachSessionResult,
        AttachmentInfo,
        CloseSessionRequest,
        DetachSessionRequest,
        InputOwner,
        OpenSessionRequest,
        PluginSessionFailure,
        PluginSessionFailureCode,
        SessionCapabilities,
        SessionExitInfo,
        SessionFailure,
        SessionFailureCode,
        SessionState,
        SessionSummary,
    )
    from .secrets import (
        BitwardenStatus,
        RbwStatus,
        SecretBackendDescriptor,
        SecretBackendRegistry,
        SecretBackendState,
        SecretConfiguration,
        SecretMessageCode,
        SecretOperationResult,
        SecretOperationState,
        SecretTransferMessage,
        SecretTransferMessageCode,
        SecretTransferPreview,
        SecretTransferResult,
        SecretUnlockResult,
        UnlockResultKind,
        UpdateSecretConfigurationRequest,
    )
    from .terminal import (
        BroadcastTerminalInputRequest,
        ClaimTerminalInputRequest,
        ExternalTerminalLaunchSpec,
        ReleaseTerminalInputRequest,
        ReplayBounds,
        ReplayRequest,
        ReplayResult,
        ResizeTerminalRequest,
        TerminalDimensions,
        TerminalInput,
        TerminalOutput,
    )
    from .settings import (
        EDITABLE_FIELDS,
        GlobalSshOverrides,
        UpdateGlobalSshOverridesRequest,
    )
    from .transfers import (
        StartScpTransferRequest,
        TransferBackend,
        CancelTransferRequest,
        StartTransferRequest,
        TransferConflictPolicy,
        TransferDirection,
        TransferLocalMode,
        TransferState,
        TransferSummary,
    )
    

__all__ = [
    "EDITABLE_CONFIG_FIELDS",
    "EDITABLE_FIELDS",
    "FORBIDDEN_IN_PATCH",
    "UNSET",
    "AddTagToConnectionsRequest",
    "AgentKey",
    "AgentKeyList",
    "AgentKeyMutationRequest",
    "AsbruImportMessage",
    "AsbruImportMessageCode",
    "AsbruImportMode",
    "AsbruImportPreview",
    "AsbruImportRequest",
    "AsbruImportResult",
    "AssignConnectionToGroupRequest",
    "AttachSessionRequest",
    "AttachSessionResult",
    "AttachSftpRequest",
    "AttachmentId",
    "AttachmentInfo",
    "AuthenticationMethod",
    "AuthorizedKeyEntry",
    "AuthorizedKeyLineKind",
    "AuthorizedKeyList",
    "BitwardenStatus",
    "BroadcastCommandOutput",
    "BroadcastCommandRequest",
    "BroadcastCommandSummary",
    "BroadcastExecutionPolicy",
    "BroadcastFailurePolicy",
    "BroadcastTerminalInputRequest",
    "CancelTransferRequest",
    "ChallengePrompt",
    "ClaimForwardRequest",
    "ClaimTerminalInputRequest",
    "ClientId",
    "ClientInfo",
    "CloseForwardRequest",
    "CloseSessionRequest",
    "CloseSftpRequest",
    "CompatibilityResult",
    "ConfirmationPrompt",
    "ConnectionDetails",
    "ConnectionEditorCapabilities",
    "ConnectionEditorDetails",
    "ConnectionHealth",
    "ConnectionId",
    "ConnectionMetadataSummary",
    "ConnectionMutationResult",
    "ConnectionPlacementMode",
    "ConnectionStoreSnapshot",
    "ConnectionSummary",
    "ConnectionValidationError",
    "ConnectionValidationResult",
    "CopyConnectionToGroupRequest",
    "CoreInfo",
    "CpuInfo",
    "CpuTimes",
    "CpuUtilization",
    "CreateConnectionRequest",
    "CreateGroupRequest",
    "DaemonDiagnostics",
    "DaemonDisconnectReason",
    "DaemonIdleInfo",
    "DaemonLifecycleState",
    "DaemonLogLevel",
    "DaemonResourceCounts",
    "DaemonStatus",
    "DaemonStopResult",
    "DeleteConnectionPasswordRequest",
    "DeleteConnectionRequest",
    "DeleteConnectionResult",
    "DeleteGroupRequest",
    "DeleteKeyPassphraseRequest",
    "DeleteKeyRequest",
    "DeleteKeyResult",
    "DeletePluginSecretRequest",
    "DeployKeyRequest",
    "DetachSessionRequest",
    "EffectiveConfigComparison",
    "ExecutionInteractionMode",
    "ExternalTerminalLaunchSpec",
    "FailedUnit",
    "FetchPublicKeysRequest",
    "FileEntryKind",
    "FilesystemUsage",
    "ForwardId",
    "ForwardKind",
    "ForwardState",
    "ForwardSummary",
    "ForwardType",
    "ForwardingRule",
    "GenerateKeyRequest",
    "GenerateKeyResult",
    "GetPluginSecretRequest",
    "GlobalSshOverrides",
    "GroupId",
    "GroupReference",
    "GroupSummary",
    "HostCommandResult",
    "HostCommandState",
    "HostInfoFailure",
    "HostInfoFailureCode",
    "HostInfoProbe",
    "HostInfoRequest",
    "HostInfoSnapshot",
    "HostInfoSummary",
    "HostKeyDecision",
    "HostKeyFingerprint",
    "HostKeyPrompt",
    "HostKeyStatus",
    "IdentityFailure",
    "IdentityFailureCode",
    "IdentityProviderDescriptor",
    "IdentityProviderRegistry",
    "IdentityState",
    "ImportedPublicKey",
    "ImportedPublicKeyList",
    "InputOwner",
    "InteractionCancellation",
    "InteractionClaim",
    "InteractionDecisionRequest",
    "InteractionId",
    "InteractionKind",
    "InteractionPrompt",
    "InteractionRejection",
    "InteractionRequest",
    "InteractionResponse",
    "InteractionState",
    "InteractionStatus",
    "InteractionSummary",
    "InteractionTimeout",
    "InteractionType",
    "InterfaceCounters",
    "KeyId",
    "KeyList",
    "KeyStoreScope",
    "KeySummary",
    "KnownHostEntryId",
    "KnownHostEntrySummary",
    "KnownHostsMutationResult",
    "KnownHostsSnapshot",
    "ListAuthorizedKeysRequest",
    "ListDirectoryRequest",
    "ListDirectoryResult",
    "ListKeysRequest",
    "ListeningPort",
    "LiveSample",
    "LoadAverage",
    "LoginSession",
    "LookupKeyPassphraseRequest",
    "MemoryInfo",
    "MoveConnectionsRequest",
    "NetworkInterface",
    "NetworkInterfaceKind",
    "NetworkInterfaceState",
    "OpenForwardRequest",
    "OpenSessionRequest",
    "OpenSftpRequest",
    "OperationId",
    "OperationKind",
    "OperationMode",
    "OperationModeFiles",
    "OperationModeResult",
    "OperationState",
    "OperationSummary",
    "PassphrasePrompt",
    "PasswordPrompt",
    "PlaceGroupRequest",
    "PluginArgument",
    "PluginOperationRequest",
    "PluginOperationResult",
    "PluginSessionFailure",
    "PluginSessionFailureCode",
    "PortForwardSummary",
    "PreCommandLaunchKind",
    "PreCommandMode",
    "PreCommandPhase",
    "PreCommandReason",
    "PreCommandStage",
    "PreConnectionCommandNotice",
    "PresencePrompt",
    "PressureStall",
    "ProcessCounts",
    "ProcessUsage",
    "PublicKeyResult",
    "RbwStatus",
    "ReadPublicKeyRequest",
    "ReleaseTerminalInputRequest",
    "RememberPolicy",
    "RemoteFileEntry",
    "RemoteFileType",
    "RemoveAuthorizedKeyRequest",
    "RemoveConnectionFromGroupRequest",
    "RemoveKnownHostEntriesRequest",
    "RenameGroupRequest",
    "RenameTagRequest",
    "ReorderConnectionRequest",
    "ReplayBounds",
    "ReplayRequest",
    "ReplayResult",
    "RequestId",
    "ResizeTerminalRequest",
    "RestartDaemonRequest",
    "SaveSshConfigTextRequest",
    "ScpFailure",
    "ScpFailureCode",
    "SecretBackendDescriptor",
    "SecretBackendRegistry",
    "SecretBackendState",
    "SecretConfiguration",
    "SecretDecision",
    "SecretMessageCode",
    "SecretOperationResult",
    "SecretOperationState",
    "SecretPromptKind",
    "SecretTransferMessage",
    "SecretTransferMessageCode",
    "SecretTransferPreview",
    "SecretTransferResult",
    "SecretUnlockResult",
    "ServiceFailure",
    "SessionCapabilities",
    "SessionExitInfo",
    "SessionFailure",
    "SessionFailureCode",
    "SessionId",
    "SessionState",
    "SessionSummary",
    "SetDaemonLogLevelRequest",
    "SetGroupColorRequest",
    "SetOperationModeRequest",
    "SetSessionConnectionPasswordRequest",
    "SftpChmodRequest",
    "SftpCopyRequest",
    "SftpCreateFileRequest",
    "SftpCreateFileResult",
    "SftpDirectorySizeRequest",
    "SftpDirectorySizeResult",
    "SftpEntry",
    "SftpFailure",
    "SftpFailureCode",
    "SftpFileAccess",
    "SftpFileTarget",
    "SftpFilesystemUsage",
    "SftpPathRequest",
    "SftpRemoveFailure",
    "SftpRemoveResult",
    "SftpReadFileRequest",
    "SftpReadFileResult",
    "SftpRenameRequest",
    "SftpReplaceFileRequest",
    "SftpReplaceFileResult",
    "SftpServiceId",
    "SftpServiceState",
    "SftpServiceSummary",
    "SftpSymlinkRequest",
    "SocketConnection",
    "SocketDirection",
    "SplitConnectionRequest",
    "SshConfigText",
    "StartScpTransferRequest",
    "StartTransferRequest",
    "StopDaemonRequest",
    "StoreConnectionPasswordRequest",
    "StoreKeyPassphraseRequest",
    "StorePluginSecretRequest",
    "TemperatureReading",
    "TerminalDimensions",
    "TerminalInput",
    "TerminalOutput",
    "TransferBackend",
    "TransferConflictPolicy",
    "TransferDirection",
    "TransferId",
    "TransferLocalMode",
    "TransferState",
    "TransferSummary",
    "UnlockResultKind",
    "UnsavedHostCheckRequest",
    "UnsavedHostCheckResult",
    "UpdateConnectionMetadataRequest",
    "UpdateConnectionRequest",
    "UpdateGlobalSshOverridesRequest",
    "UpdateIdentityConfigurationRequest",
    "UpdateIdentitySelectionRequest",
    "UpdateSecretConfigurationRequest",
    "VerifyKeyPassphraseRequest",
    "VerifyKeyPassphraseResult",
    "default_idle_shutdown_seconds",
    "forwarding_rule_from_dict",
    "forwarding_rule_to_dict",
    "is_terminal_operation_state",
    "is_valid_lifecycle_transition",
    "is_valid_operation_transition",
    "validate_config_patch",
]

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AddTagToConnectionsRequest": ("connection_store", "AddTagToConnectionsRequest"),
    "AgentKey": ("identity", "AgentKey"),
    "AgentKeyList": ("identity", "AgentKeyList"),
    "AgentKeyMutationRequest": ("identity", "AgentKeyMutationRequest"),
    "AsbruImportMessage": ("connections", "AsbruImportMessage"),
    "AsbruImportMessageCode": ("connections", "AsbruImportMessageCode"),
    "AsbruImportMode": ("connections", "AsbruImportMode"),
    "AsbruImportPreview": ("connections", "AsbruImportPreview"),
    "AsbruImportRequest": ("connections", "AsbruImportRequest"),
    "AsbruImportResult": ("connections", "AsbruImportResult"),
    "AssignConnectionToGroupRequest": ("connections", "AssignConnectionToGroupRequest"),
    "AttachSessionRequest": ("sessions", "AttachSessionRequest"),
    "AttachSessionResult": ("sessions", "AttachSessionResult"),
    "AttachSftpRequest": ("operations", "AttachSftpRequest"),
    "AttachmentId": ("common", "AttachmentId"),
    "AttachmentInfo": ("sessions", "AttachmentInfo"),
    "AuthenticationMethod": ("connections", "AuthenticationMethod"),
    "AuthorizedKeyEntry": ("identity", "AuthorizedKeyEntry"),
    "AuthorizedKeyLineKind": ("identity", "AuthorizedKeyLineKind"),
    "AuthorizedKeyList": ("identity", "AuthorizedKeyList"),
    "BitwardenStatus": ("secrets", "BitwardenStatus"),
    "BroadcastCommandOutput": ("broadcast", "BroadcastCommandOutput"),
    "BroadcastCommandRequest": ("broadcast", "BroadcastCommandRequest"),
    "BroadcastCommandSummary": ("broadcast", "BroadcastCommandSummary"),
    "BroadcastExecutionPolicy": ("broadcast", "BroadcastExecutionPolicy"),
    "BroadcastFailurePolicy": ("broadcast", "BroadcastFailurePolicy"),
    "BroadcastTerminalInputRequest": ("terminal", "BroadcastTerminalInputRequest"),
    "CancelTransferRequest": ("transfers", "CancelTransferRequest"),
    "ChallengePrompt": ("interactions", "ChallengePrompt"),
    "ClaimForwardRequest": ("operations", "ClaimForwardRequest"),
    "ClaimTerminalInputRequest": ("terminal", "ClaimTerminalInputRequest"),
    "ClientId": ("common", "ClientId"),
    "ClientInfo": ("common", "ClientInfo"),
    "CloseForwardRequest": ("operations", "CloseForwardRequest"),
    "CloseSessionRequest": ("sessions", "CloseSessionRequest"),
    "CloseSftpRequest": ("operations", "CloseSftpRequest"),
    "CompatibilityResult": ("common", "CompatibilityResult"),
    "ConfirmationPrompt": ("interactions", "ConfirmationPrompt"),
    "ConnectionDetails": ("connections", "ConnectionDetails"),
    "ConnectionEditorCapabilities": ("connections", "ConnectionEditorCapabilities"),
    "ConnectionEditorDetails": ("connections", "ConnectionEditorDetails"),
    "ConnectionHealth": ("connections", "ConnectionHealth"),
    "ConnectionId": ("common", "ConnectionId"),
    "ConnectionMetadataSummary": ("connection_store", "ConnectionMetadataSummary"),
    "ConnectionMutationResult": ("connections", "ConnectionMutationResult"),
    "ConnectionPlacementMode": ("connection_store", "ConnectionPlacementMode"),
    "ConnectionStoreSnapshot": ("connection_store", "ConnectionStoreSnapshot"),
    "ConnectionSummary": ("connections", "ConnectionSummary"),
    "ConnectionValidationError": ("connections", "ConnectionValidationError"),
    "ConnectionValidationResult": ("connections", "ConnectionValidationResult"),
    "CopyConnectionToGroupRequest": ("connection_store", "CopyConnectionToGroupRequest"),
    "CoreInfo": ("common", "CoreInfo"),
    "CpuInfo": ("host_info", "CpuInfo"),
    "CpuTimes": ("host_info", "CpuTimes"),
    "CpuUtilization": ("host_info", "CpuUtilization"),
    "CreateConnectionRequest": ("connections", "CreateConnectionRequest"),
    "CreateGroupRequest": ("connections", "CreateGroupRequest"),
    "DaemonDiagnostics": ("daemon", "DaemonDiagnostics"),
    "DaemonDisconnectReason": ("daemon", "DaemonDisconnectReason"),
    "DaemonIdleInfo": ("daemon", "DaemonIdleInfo"),
    "DaemonLifecycleState": ("daemon", "DaemonLifecycleState"),
    "DaemonLogLevel": ("daemon", "DaemonLogLevel"),
    "DaemonResourceCounts": ("daemon", "DaemonResourceCounts"),
    "DaemonStatus": ("daemon", "DaemonStatus"),
    "DaemonStopResult": ("daemon", "DaemonStopResult"),
    "DeleteConnectionPasswordRequest": ("connections", "DeleteConnectionPasswordRequest"),
    "DeleteConnectionRequest": ("connections", "DeleteConnectionRequest"),
    "DeleteConnectionResult": ("connections", "DeleteConnectionResult"),
    "DeleteGroupRequest": ("connections", "DeleteGroupRequest"),
    "DeleteKeyPassphraseRequest": ("connections", "DeleteKeyPassphraseRequest"),
    "DeleteKeyRequest": ("keys", "DeleteKeyRequest"),
    "DeleteKeyResult": ("keys", "DeleteKeyResult"),
    "DeletePluginSecretRequest": ("connections", "DeletePluginSecretRequest"),
    "DeployKeyRequest": ("identity", "DeployKeyRequest"),
    "DetachSessionRequest": ("sessions", "DetachSessionRequest"),
    "EDITABLE_CONFIG_FIELDS": ("connections", "EDITABLE_CONFIG_FIELDS"),
    "EDITABLE_FIELDS": ("settings", "EDITABLE_FIELDS"),
    "EffectiveConfigComparison": ("connections", "EffectiveConfigComparison"),
    "ExecutionInteractionMode": ("interactions", "ExecutionInteractionMode"),
    "ExternalTerminalLaunchSpec": ("terminal", "ExternalTerminalLaunchSpec"),
    "FORBIDDEN_IN_PATCH": ("connections", "FORBIDDEN_IN_PATCH"),
    "FailedUnit": ("host_info", "FailedUnit"),
    "FetchPublicKeysRequest": ("identity", "FetchPublicKeysRequest"),
    "FileEntryKind": ("operations", "FileEntryKind"),
    "FilesystemUsage": ("host_info", "FilesystemUsage"),
    "ForwardId": ("common", "ForwardId"),
    "ForwardKind": ("operations", "ForwardKind"),
    "ForwardState": ("operations", "ForwardState"),
    "ForwardSummary": ("operations", "ForwardSummary"),
    "ForwardType": ("operations", "ForwardType"),
    "ForwardingRule": ("connections", "ForwardingRule"),
    "GenerateKeyRequest": ("keys", "GenerateKeyRequest"),
    "GenerateKeyResult": ("keys", "GenerateKeyResult"),
    "GetPluginSecretRequest": ("connections", "GetPluginSecretRequest"),
    "GlobalSshOverrides": ("settings", "GlobalSshOverrides"),
    "GroupId": ("connection_store", "GroupId"),
    "GroupReference": ("connections", "GroupReference"),
    "GroupSummary": ("connection_store", "GroupSummary"),
    "HostCommandResult": ("broadcast", "HostCommandResult"),
    "HostCommandState": ("broadcast", "HostCommandState"),
    "HostInfoFailure": ("host_info", "HostInfoFailure"),
    "HostInfoFailureCode": ("host_info", "HostInfoFailureCode"),
    "HostInfoProbe": ("host_info", "HostInfoProbe"),
    "HostInfoRequest": ("host_info", "HostInfoRequest"),
    "HostInfoSnapshot": ("host_info", "HostInfoSnapshot"),
    "HostInfoSummary": ("host_info", "HostInfoSummary"),
    "HostKeyDecision": ("interactions", "HostKeyDecision"),
    "HostKeyFingerprint": ("host_info", "HostKeyFingerprint"),
    "HostKeyPrompt": ("interactions", "HostKeyPrompt"),
    "HostKeyStatus": ("interactions", "HostKeyStatus"),
    "IdentityFailure": ("operations", "IdentityFailure"),
    "IdentityFailureCode": ("operations", "IdentityFailureCode"),
    "IdentityProviderDescriptor": ("identity", "IdentityProviderDescriptor"),
    "IdentityProviderRegistry": ("identity", "IdentityProviderRegistry"),
    "IdentityState": ("identity", "IdentityState"),
    "ImportedPublicKey": ("identity", "ImportedPublicKey"),
    "ImportedPublicKeyList": ("identity", "ImportedPublicKeyList"),
    "InputOwner": ("sessions", "InputOwner"),
    "InteractionCancellation": ("interactions", "InteractionCancellation"),
    "InteractionClaim": ("interactions", "InteractionClaim"),
    "InteractionDecisionRequest": ("interactions", "InteractionDecisionRequest"),
    "InteractionId": ("common", "InteractionId"),
    "InteractionKind": ("interactions", "InteractionKind"),
    "InteractionPrompt": ("interactions", "InteractionPrompt"),
    "InteractionRejection": ("interactions", "InteractionRejection"),
    "InteractionRequest": ("interactions", "InteractionRequest"),
    "InteractionResponse": ("interactions", "InteractionResponse"),
    "InteractionState": ("interactions", "InteractionState"),
    "InteractionStatus": ("interactions", "InteractionStatus"),
    "InteractionSummary": ("interactions", "InteractionSummary"),
    "InteractionTimeout": ("interactions", "InteractionTimeout"),
    "InteractionType": ("interactions", "InteractionType"),
    "InterfaceCounters": ("host_info", "InterfaceCounters"),
    "KeyId": ("keys", "KeyId"),
    "KeyList": ("keys", "KeyList"),
    "KeyStoreScope": ("keys", "KeyStoreScope"),
    "KeySummary": ("keys", "KeySummary"),
    "KnownHostEntryId": ("known_hosts", "KnownHostEntryId"),
    "KnownHostEntrySummary": ("known_hosts", "KnownHostEntrySummary"),
    "KnownHostsMutationResult": ("known_hosts", "KnownHostsMutationResult"),
    "KnownHostsSnapshot": ("known_hosts", "KnownHostsSnapshot"),
    "ListAuthorizedKeysRequest": ("identity", "ListAuthorizedKeysRequest"),
    "ListDirectoryRequest": ("operations", "ListDirectoryRequest"),
    "ListDirectoryResult": ("operations", "ListDirectoryResult"),
    "ListKeysRequest": ("keys", "ListKeysRequest"),
    "ListeningPort": ("host_info", "ListeningPort"),
    "LiveSample": ("host_info", "LiveSample"),
    "LoadAverage": ("host_info", "LoadAverage"),
    "LoginSession": ("host_info", "LoginSession"),
    "LookupKeyPassphraseRequest": ("connections", "LookupKeyPassphraseRequest"),
    "MemoryInfo": ("host_info", "MemoryInfo"),
    "MoveConnectionsRequest": ("connection_store", "MoveConnectionsRequest"),
    "NetworkInterface": ("host_info", "NetworkInterface"),
    "NetworkInterfaceKind": ("host_info", "NetworkInterfaceKind"),
    "NetworkInterfaceState": ("host_info", "NetworkInterfaceState"),
    "OpenForwardRequest": ("operations", "OpenForwardRequest"),
    "OpenSessionRequest": ("sessions", "OpenSessionRequest"),
    "OpenSftpRequest": ("operations", "OpenSftpRequest"),
    "OperationId": ("operations", "OperationId"),
    "OperationKind": ("operations", "OperationKind"),
    "OperationMode": ("daemon", "OperationMode"),
    "OperationModeFiles": ("daemon", "OperationModeFiles"),
    "OperationModeResult": ("daemon", "OperationModeResult"),
    "OperationState": ("operations", "OperationState"),
    "OperationSummary": ("operations", "OperationSummary"),
    "PassphrasePrompt": ("interactions", "PassphrasePrompt"),
    "PasswordPrompt": ("interactions", "PasswordPrompt"),
    "PlaceGroupRequest": ("connection_store", "PlaceGroupRequest"),
    "PluginArgument": ("operations", "PluginArgument"),
    "PluginOperationRequest": ("operations", "PluginOperationRequest"),
    "PluginOperationResult": ("operations", "PluginOperationResult"),
    "PreCommandLaunchKind": ("pre_command", "PreCommandLaunchKind"),
    "PreCommandMode": ("pre_command", "PreCommandMode"),
    "PreCommandPhase": ("pre_command", "PreCommandPhase"),
    "PreCommandReason": ("pre_command", "PreCommandReason"),
    "PreCommandStage": ("pre_command", "PreCommandStage"),
    "PreConnectionCommandNotice": ("pre_command", "PreConnectionCommandNotice"),
    "PluginSessionFailure": ("sessions", "PluginSessionFailure"),
    "PluginSessionFailureCode": ("sessions", "PluginSessionFailureCode"),
    "PortForwardSummary": ("operations", "PortForwardSummary"),
    "PresencePrompt": ("interactions", "PresencePrompt"),
    "PressureStall": ("host_info", "PressureStall"),
    "ProcessCounts": ("host_info", "ProcessCounts"),
    "ProcessUsage": ("host_info", "ProcessUsage"),
    "PublicKeyResult": ("keys", "PublicKeyResult"),
    "RbwStatus": ("secrets", "RbwStatus"),
    "ReadPublicKeyRequest": ("keys", "ReadPublicKeyRequest"),
    "ReleaseTerminalInputRequest": ("terminal", "ReleaseTerminalInputRequest"),
    "RememberPolicy": ("interactions", "RememberPolicy"),
    "RemoteFileEntry": ("operations", "RemoteFileEntry"),
    "RemoteFileType": ("operations", "RemoteFileType"),
    "RemoveAuthorizedKeyRequest": ("identity", "RemoveAuthorizedKeyRequest"),
    "RemoveConnectionFromGroupRequest": ("connection_store", "RemoveConnectionFromGroupRequest"),
    "RemoveKnownHostEntriesRequest": ("known_hosts", "RemoveKnownHostEntriesRequest"),
    "RenameGroupRequest": ("connections", "RenameGroupRequest"),
    "RenameTagRequest": ("connection_store", "RenameTagRequest"),
    "ReorderConnectionRequest": ("connection_store", "ReorderConnectionRequest"),
    "ReplayBounds": ("terminal", "ReplayBounds"),
    "ReplayRequest": ("terminal", "ReplayRequest"),
    "ReplayResult": ("terminal", "ReplayResult"),
    "RequestId": ("common", "RequestId"),
    "ResizeTerminalRequest": ("terminal", "ResizeTerminalRequest"),
    "RestartDaemonRequest": ("daemon", "RestartDaemonRequest"),
    "SaveSshConfigTextRequest": ("connections", "SaveSshConfigTextRequest"),
    "ScpFailure": ("operations", "ScpFailure"),
    "ScpFailureCode": ("operations", "ScpFailureCode"),
    "SecretBackendDescriptor": ("secrets", "SecretBackendDescriptor"),
    "SecretBackendRegistry": ("secrets", "SecretBackendRegistry"),
    "SecretBackendState": ("secrets", "SecretBackendState"),
    "SecretConfiguration": ("secrets", "SecretConfiguration"),
    "SecretDecision": ("interactions", "SecretDecision"),
    "SecretMessageCode": ("secrets", "SecretMessageCode"),
    "SecretOperationResult": ("secrets", "SecretOperationResult"),
    "SecretOperationState": ("secrets", "SecretOperationState"),
    "SecretPromptKind": ("interactions", "SecretPromptKind"),
    "SecretTransferMessage": ("secrets", "SecretTransferMessage"),
    "SecretTransferMessageCode": ("secrets", "SecretTransferMessageCode"),
    "SecretTransferPreview": ("secrets", "SecretTransferPreview"),
    "SecretTransferResult": ("secrets", "SecretTransferResult"),
    "SecretUnlockResult": ("secrets", "SecretUnlockResult"),
    "ServiceFailure": ("operations", "ServiceFailure"),
    "SessionCapabilities": ("sessions", "SessionCapabilities"),
    "SessionExitInfo": ("sessions", "SessionExitInfo"),
    "SessionFailure": ("sessions", "SessionFailure"),
    "SessionFailureCode": ("sessions", "SessionFailureCode"),
    "SessionId": ("common", "SessionId"),
    "SessionState": ("sessions", "SessionState"),
    "SessionSummary": ("sessions", "SessionSummary"),
    "SetDaemonLogLevelRequest": ("daemon", "SetDaemonLogLevelRequest"),
    "SetGroupColorRequest": ("connection_store", "SetGroupColorRequest"),
    "SetOperationModeRequest": ("daemon", "SetOperationModeRequest"),
    "SetSessionConnectionPasswordRequest": ("connections", "SetSessionConnectionPasswordRequest"),
    "SftpChmodRequest": ("operations", "SftpChmodRequest"),
    "SftpCopyRequest": ("operations", "SftpCopyRequest"),
    "SftpCreateFileRequest": ("operations", "SftpCreateFileRequest"),
    "SftpCreateFileResult": ("operations", "SftpCreateFileResult"),
    "SftpDirectorySizeRequest": ("operations", "SftpDirectorySizeRequest"),
    "SftpDirectorySizeResult": ("operations", "SftpDirectorySizeResult"),
    "SftpEntry": ("operations", "SftpEntry"),
    "SftpFailure": ("operations", "SftpFailure"),
    "SftpFailureCode": ("operations", "SftpFailureCode"),
    "SftpFilesystemUsage": ("operations", "SftpFilesystemUsage"),
    "SftpFileAccess": ("operations", "SftpFileAccess"),
    "SftpFileTarget": ("operations", "SftpFileTarget"),
    "SftpPathRequest": ("operations", "SftpPathRequest"),
    "SftpRemoveFailure": ("operations", "SftpRemoveFailure"),
    "SftpRemoveResult": ("operations", "SftpRemoveResult"),
    "SftpReadFileRequest": ("operations", "SftpReadFileRequest"),
    "SftpReadFileResult": ("operations", "SftpReadFileResult"),
    "SftpRenameRequest": ("operations", "SftpRenameRequest"),
    "SftpReplaceFileRequest": ("operations", "SftpReplaceFileRequest"),
    "SftpReplaceFileResult": ("operations", "SftpReplaceFileResult"),
    "SftpServiceId": ("common", "SftpServiceId"),
    "SftpServiceState": ("operations", "SftpServiceState"),
    "SftpServiceSummary": ("operations", "SftpServiceSummary"),
    "SftpSymlinkRequest": ("operations", "SftpSymlinkRequest"),
    "SocketConnection": ("host_info", "SocketConnection"),
    "SocketDirection": ("host_info", "SocketDirection"),
    "SplitConnectionRequest": ("connections", "SplitConnectionRequest"),
    "SshConfigText": ("connections", "SshConfigText"),
    "StartScpTransferRequest": ("transfers", "StartScpTransferRequest"),
    "StartTransferRequest": ("transfers", "StartTransferRequest"),
    "StopDaemonRequest": ("daemon", "StopDaemonRequest"),
    "StoreConnectionPasswordRequest": ("connections", "StoreConnectionPasswordRequest"),
    "StoreKeyPassphraseRequest": ("connections", "StoreKeyPassphraseRequest"),
    "StorePluginSecretRequest": ("connections", "StorePluginSecretRequest"),
    "TemperatureReading": ("host_info", "TemperatureReading"),
    "TerminalDimensions": ("terminal", "TerminalDimensions"),
    "TerminalInput": ("terminal", "TerminalInput"),
    "TerminalOutput": ("terminal", "TerminalOutput"),
    "TransferBackend": ("transfers", "TransferBackend"),
    "TransferConflictPolicy": ("transfers", "TransferConflictPolicy"),
    "TransferDirection": ("transfers", "TransferDirection"),
    "TransferId": ("common", "TransferId"),
    "TransferLocalMode": ("transfers", "TransferLocalMode"),
    "TransferState": ("transfers", "TransferState"),
    "TransferSummary": ("transfers", "TransferSummary"),
    "UNSET": ("connections", "UNSET"),
    "UnlockResultKind": ("secrets", "UnlockResultKind"),
    "UnsavedHostCheckRequest": ("connections", "UnsavedHostCheckRequest"),
    "UnsavedHostCheckResult": ("connections", "UnsavedHostCheckResult"),
    "UpdateConnectionMetadataRequest": ("connections", "UpdateConnectionMetadataRequest"),
    "UpdateConnectionRequest": ("connections", "UpdateConnectionRequest"),
    "UpdateGlobalSshOverridesRequest": ("settings", "UpdateGlobalSshOverridesRequest"),
    "UpdateIdentityConfigurationRequest": ("identity", "UpdateIdentityConfigurationRequest"),
    "UpdateIdentitySelectionRequest": ("identity", "UpdateIdentitySelectionRequest"),
    "UpdateSecretConfigurationRequest": ("secrets", "UpdateSecretConfigurationRequest"),
    "VerifyKeyPassphraseRequest": ("keys", "VerifyKeyPassphraseRequest"),
    "VerifyKeyPassphraseResult": ("keys", "VerifyKeyPassphraseResult"),
    "default_idle_shutdown_seconds": ("daemon", "default_idle_shutdown_seconds"),
    "forwarding_rule_from_dict": ("connections", "forwarding_rule_from_dict"),
    "forwarding_rule_to_dict": ("connections", "forwarding_rule_to_dict"),
    "is_terminal_operation_state": ("operations", "is_terminal_operation_state"),
    "is_valid_lifecycle_transition": ("daemon", "is_valid_lifecycle_transition"),
    "is_valid_operation_transition": ("operations", "is_valid_operation_transition"),
    "validate_config_patch": ("connections", "validate_config_patch"),
}

def __getattr__(name: str) -> Any:
    target = _LAZY_EXPORTS.get(name)
    if target is not None:
        mod_name, attr_name = target
        mod = import_module(f".{mod_name}", __name__)
        val = getattr(mod, attr_name)
        globals()[name] = val
        return val
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals().keys()) | set(__all__))
