name: Tests

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-gi python3-gi-cairo \
            gir1.2-gtk-4.0 gir1.2-adw-1 \
            libgtk-4-1 libadwaita-1-0 \
            libvte-2.91-gtk4-0 gir1.2-vte-3.91 \
            python3-dogtail at-spi2-core \
            xvfb dbus-x11

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run unit and integration tests
        run: |
          xvfb-run -s "-screen 0 1024x768x24" \
            dbus-run-session -- \
            pytest -m "not e2e"

      - name: Run end-to-end tests
        if: github.ref == 'refs/heads/main'
        run: |
          xvfb-run -s "-screen 0 1024x768x24" \
            dbus-run-session -- \
            pytest -m e2e tests_e2e
